on:
  push:
    branches:
      - master
    
jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      TOKEN_OPENZH: ${{ secrets.TOKEN_OPENZH }}

    steps:
    - uses: actions/checkout@master
    
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - name: Install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
        
    - name: Query dependencies
      run: |
          install.packages('dplyr')
          install.packages('purrr')
          install.packages('tidyr')
          install.packages('curl')
          install.packages('crul')
          install.packages('ckanr')          
      shell: Rscript {0}
        
    - run: Rscript -e 'source("template.R")'
    
    - name: Update Datasets
      run: |
          source("template.R")
      shell: Rscript {0} 
    
    - name: Commit files
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
